### ISSUE TITLE
Harmony Hub listed as one device and shown as not supported.

### ISSUE THREAD

**Issue by homohurre123** [materik/homebridge-harmonyhub#7]
I added you plugin with the latest version to my Homebridge running on Raspberry Pi with the Homebridge App.
Now I can see "Harmony Hub" as one device which isn't supported and It doesn't detect the Scenes I have saved. Any Idea what could be the reason and how to help me? Homebridge is stable beside this.
Thanks a lot for your effort in advance!

**Comment by homohurre123** [comment]
Nevermind It was my Bad because my Harmony had an Issue on its own. Great Work Dude!

**Comment by materik** [comment]
:+1:
