### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by twynne** [materik/homebridge-harmonyhub#9]
Trying to move to this from the old Harmony platform plugin (which I've now removed), but install fails.  Log shows the following:

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.11.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'materik/homebridge-harmonyhub#0.4.0' ]
2 info using npm@6.4.1
3 info using node@v10.11.0
4 verbose npm-session 23e22a8bb8938145
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for github:materik/homebridge-harmonyhub#0.4.0 Command failed: /usr/bin/git clone --depth=1 -q -b 0.4.0 git://github.com/materik/homebridge-harmonyhub.git /Users/homeserver/.npm/_cacache/tmp/git-clone-0ce25ba5
7 silly fetchPackageMetaData /Users/homeserver/.npm/_cacache/tmp/git-clone-0ce25ba5/.git: Permission denied
8 timing stage:rollbackFailedOptional Completed in 1ms
9 timing stage:runTopLevelLifecycles Completed in 578ms
10 verbose stack Error: Command failed: /usr/bin/git clone --depth=1 -q -b 0.4.0 git://github.com/materik/homebridge-harmonyhub.git /Users/homeserver/.npm/_cacache/tmp/git-clone-0ce25ba5
10 verbose stack /Users/homeserver/.npm/_cacache/tmp/git-clone-0ce25ba5/.git: Permission denied
10 verbose stack
10 verbose stack     at ChildProcess.exithandler (child_process.js:289:12)
10 verbose stack     at ChildProcess.emit (events.js:182:13)
10 verbose stack     at maybeClose (internal/child_process.js:962:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
11 verbose cwd /Users/homeserver
12 verbose Darwin 17.7.0
13 verbose argv "/usr/local/Cellar/node/10.11.0/bin/node" "/usr/local/bin/npm" "install" "-g" "materik/homebridge-harmonyhub#0.4.0"
14 verbose node v10.11.0
15 verbose npm  v6.4.1
16 error code 1
17 error Command failed: /usr/bin/git clone --depth=1 -q -b 0.4.0 git://github.com/materik/homebridge-harmonyhub.git /Users/homeserver/.npm/_cacache/tmp/git-clone-0ce25ba5
17 error /Users/homeserver/.npm/_cacache/tmp/git-clone-0ce25ba5/.git: Permission denied
18 verbose exit [ 1, true ]

**Comment by materik** [comment]
you seem to get a permission denied for some reason. don't think it's related to the package 🤞

**Comment by DJay-X** [comment]
@twynne try

`sudo chown -R $USER /usr/local && npm install materik/homebridge-harmonyhub#0.4.0 -g`

**Comment by twynne** [comment]
Thanks @DJay-X .. sadly I get 'Operation not permitted'... afraid I'm not much of a terminal expert.  Anything obvious?

**Comment by twynne** [comment]
Managed to get it going, though I've no idea what changed as the change permissions didn't appear to work.  Anyway now that it's installed, I'm seeing the same issue as another person posted that it only picks up 1 of 2 hubs.  Will post about that elsewhere.

Thanks for help. :)
